version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "next-auth"
  - package-ecosystem: "npm"
    directory: "/playground"
    schedule:
      interval: "weekly"
