services:
  web:
    build:
      context: .docker
      target: builder
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    volumes:
      - .:/app
    # entrypoint: ["python"]
    # command: ["manage.py", "runserver", "0.0.0.0:8000"]

  mongodb:
    image: mongo
    # volumes:
    #   - ./data-db:/data/db
    ports:
      - 27017:27017
