volumes:
  docs_app_db:

services:
  frontend:
    build:
      context: .
      dockerfile: .docker/frontend.Dockerfile
    ports:
      - "8001:8080"
    volumes:
      - ./frontend:/app

  backend:
    build:
      context: .
      dockerfile: .docker/backend.Dockerfile
      target: builder
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/app
    entrypoint: ["python"]
    command: ["manage.py", "runserver", "0.0.0.0:8000"]

  db:
    image: mongo
    volumes:
      - docs_app_db:/data/db
    ports:
      - 27017:27017

  # migration:
#     build: .
#     image: app
#     command: python manage.py migrate
#     volumes:
#       - .:/django_mongodb_docker
#     links:
#       - mongodb
#     depends_on:
#       - make_migrations
#
#   make_migrations:
#     build: .
#     image: app
#     command: python manage.py makemigrations
#     volumes:
#       - .:/django_mongodb_docker
#     links:
#       - mongodb
#     depends_on:
#       - mongodb
