services:
  web:
    build:
      context: .
      target: builder
    volumes:
      - ../app:/app
    # ports:
    #   - "8000:8000"
    # depends_on:
    #   - mongodb
    # entrypoint: ["python"]
    # command: ["manage.py", "runserver", "0.0.0.0:8000"]

  # mongodb:
  #   image: mongo
  #   # volumes:
  #   #   - ./data-db:/data/db
  #   ports:
  #     - 27017:27017
