# Generated by Django 3.2.13 on 2023-01-29 15:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='attachment',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='claim',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='claim',
            name='doc_type',
            field=models.CharField(choices=[('1', 'DGSTR'), ('2', 'STREA'), ('3', 'OSTR')], default='1', max_length=2),
        ),
        migrations.AddField(
            model_name='claim',
            name='image',
            field=models.BinaryField(blank=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='claim',
            name='priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='claim',
            name='title',
            field=models.CharField(max_length=80),
        ),
    ]
