# Generated by Django 3.2.13 on 2023-02-10 10:41

import claim.models
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0002_auto_20230129_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='documents',
            field=djongo.models.fields.ArrayField(default=[], model_container=claim.models.Document, model_form_class=claim.models.DocumentForm, null=True),
        ),
    ]
